import { Product } from './store';

export const products: Product[] = [
  {
    id: '1',
    name: 'Vela Lavanda Serenidade',
    description: 'Vela artesanal de lavanda, perfeita para momentos de relaxamento e meditação. Cera 100% natural de soja.',
    price: 89.90,
    image: 'https://images.unsplash.com/photo-1602874801007-e7b2f186c8a8?w=800&q=80',
    category: 'candle',
    scent: 'Lavanda',
    inStock: true,
  },
  {
    id: '2',
    name: 'Vela Âmbar & Baunilha',
    description: 'Uma combinação sofisticada de âmbar e baunilha que cria uma atmosfera acolhedora e luxuosa.',
    price: 95.90,
    image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=800&q=80',
    category: 'candle',
    scent: 'Âmbar & Baunilha',
    inStock: true,
  },
  {
    id: '3',
    name: 'Vela Eucalipto & Menta',
    description: 'Refrescante e revigorante, ideal para purificar o ambiente e estimular a concentração.',
    price: 87.90,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&q=80',
    category: 'candle',
    scent: 'Eucalipto & Menta',
    inStock: true,
  },
  {
    id: '4',
    name: 'Vela Flor de Cerejeira',
    description: 'Delicada e floral, traz a suavidade das flores de cerejeira para seu espaço.',
    price: 92.90,
    image: 'https://images.unsplash.com/photo-1602874801007-e7b2f186c8a8?w=800&q=80',
    category: 'candle',
    scent: 'Flor de Cerejeira',
    inStock: true,
  },
  {
    id: '5',
    name: 'Óleo Essencial Lavanda',
    description: 'Óleo essencial puro de lavanda francesa. Propriedades calmantes e relaxantes. 10ml.',
    price: 54.90,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&q=80',
    category: 'oil',
    scent: 'Lavanda',
    inStock: true,
  },
  {
    id: '6',
    name: 'Óleo Essencial Eucalipto',
    description: 'Óleo essencial puro de eucalipto. Refrescante e purificante. 10ml.',
    price: 49.90,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&q=80',
    category: 'oil',
    scent: 'Eucalipto',
    inStock: true,
  },
  {
    id: '7',
    name: 'Óleo Essencial Tea Tree',
    description: 'Óleo essencial puro de tea tree. Propriedades purificantes e revitalizantes. 10ml.',
    price: 52.90,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&q=80',
    category: 'oil',
    scent: 'Tea Tree',
    inStock: true,
  },
  {
    id: '8',
    name: 'Vela Sândalo & Patchouli',
    description: 'Uma fragrância terrosa e amadeirada que promove equilíbrio e conexão interior.',
    price: 98.90,
    image: 'https://images.unsplash.com/photo-1602874801007-e7b2f186c8a8?w=800&q=80',
    category: 'candle',
    scent: 'Sândalo & Patchouli',
    inStock: true,
  },
];
